### ISSUE TITLE
srslteue internet access via eth0

### ISSUE THREAD

**Issue by zariok** [pgorczak/srslte-docker-emulated#3]
The docker container for virtual-srsue has internet access via eth0 on a "default" docker network 172.25.0.2 with the default route at 172.25.0.1

At the very least, I'd expect something at 172.16.0.x with a default route for the spgw.

To correct manually:
```
docker exec -i -t virtual-srsue bash
apt update; apt install iproute2
ip link set eth0 down
ip route add default via 172.16.0.1
```

After doing this you can see the service request on the virtual-srsepc when doing a ping via virtual-srsue, but ping has 100% packet loss.

I'm not overly familiar with docker-compose or docker for that matter, but I'd think the &ue-settings should contain **network_mode: "none"** and remove **- NET_ADMIN** to isolate the container from physical net and use the shared-memory.

However, doing that removes the ability to install iproute2 via apt.

**Comment by pgorczak** [comment]
Hi @zariok , you want to make UEs access the internet via EPC, right? I've added a section on this in the [README](https://github.com/pgorczak/srslte-docker-emulated#internet-access-for-ues) since it's probably good to know how to configure this for anyone trying this setup.

I added two dependencies in the Dockerfile, so you will need to tell docker-compose to re-build the containers when you try it

    docker-compose up --build

Thanks for pointing this out! Let me know if you run into any trouble.
